#!/bin/bash

###############
##### API #####
###############

cd ~/Code/podcast/api

printf '\ncrafting api..\n'
printf 'serving application.. \n'
php artisan serve --port 8080 --quiet &
printf 'running on localhost:8080 \n'

#---------------------------------------------------------------#


###############
##### APP #####
###############

cd ~/Code/podcast/app 

printf 'serving application.. \n'
php artisan serve -vv

